spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.1.111.135:1521:MEDB
      username: springboot
      password: 123456
    slave1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.2.212.148:3306/medb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
  thymeleaf:
    cache: false
    
jpa:
    show-sql: true
      
logging:
  level:
     com.fhzz.springbootdemo.dao : debug
      