spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.2.108.238:1521:ORCL
      username: C##PSOPUSER
      password: 123456
      logSlowSql: true
    slave1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.2.108.238:3306/medb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Fhzz@123456
      logSlowSql: true
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
      
logging:
  level:
     com.fhzz.springbootdemo.dao : debug
     